# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

## Base settings ##
url: "https://linlinzhao.github.io" #The site's Protocol and Hostname e.g. https://blog.someone.com (!!required!!)
title: Linlin
description: > #this means to ignore newlines until "base_path:"
    Linlin | 赵霖林

##* Home base settings ##
baseurl: "/"
avata_url: https://wx3.sinaimg.cn/large/73bd9e13ly1fjkqy66hl8j208c08c0td.jpg

##* Blog base settings ##
blog:
  baseurl: "/blog"
  title: Linlin's blog
  description: 恒道恒名，上下求索
  nav_lists:
    - title: About
      url: /blog/about.html
##* Artsworks base settings ##
artworks:
  baseurl: ""

## GitHub repository (if the site is hosted by GitHub) ##
repository: linlinzhao/linlinzhao.github.io
repository_tree: master

## Language & timezone ##
lang: EN # the language of your site
timezone: Europe/Germany

## Author & social ##
author:
  name: "Linlin Zhao"
  email: linlinzhao.c@gmail.com
  twitter: 
  github:  linlinzhao
  googleplus: 
  weibo: 
  douban: 

## Comment system (Disqus) ##
disqus:
  shortname: linlinzhao-github-io

## Google Analytics ##
ga_tracking_id: UA-108614850-1

## Reading quantity (LeanCloud) ##
## leancloud:
##  app_id: uAG3OhdcH8H4fxSqXLyBljA7-gzGzoHsz
##  app_key: Mzf5m9skSwYVWVXhGiYMNyXs
##  app_class: ThomasBlog

## Paginate ##
paginate: 7
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

## Plugins ##
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false
