# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

## Base settings ##
url: "https://linlinzhao.github.io" #The site's Protocol and Hostname e.g. https://blog.someone.com (!!required!!)
title: Linlin
description: > #this means to ignore newlines until "base_path:"
    Linlin | 赵霖林

##* Home base settings ##
baseurl: "/"
avata_url:

##* Blog base settings ##
blog:
  baseurl: "/blog"
  title: Linlin's blog
  description: 恒道恒名，上下求索
  nav_lists:
    - title: About
      url: /blog/about.html
##* Artsworks base settings ##
artworks:
  baseurl: ""

## GitHub repository (if the site is hosted by GitHub) ##
repository: linlinzhao/linlinzhao.github.io
repository_tree: master

## Language & timezone ##
lang: EN # the language of your site
timezone: Europe/Germany

## Author & social ##
author:
  name: "Linlin Zhao | 恒道恒名 上下求索"
  email: linlinzhao.c@gmail.com
  twitter:
  github:  linlinzhao
  googleplus:
  weibo:

# Comment system (Disqus) ##
comments:
        provider: disqus
        disqus:
        shortname: linlinzhao-github-io-1
#disqus: linlinzhao-github-io-1

## Google Analytics ##
analytics:
        provider: google
        google:
        ga_tracking_id: UA-108614850-1
        anonymize: true
## Reading quantity (LeanCloud) ##
pageview:
        provider: leancloud
        leancloud:
        app_id: um8kyIpEtaUqAGVt8QDyaaxB-gzGzoHsz
        app_key: HXR34FRahoMKDU4nQRJTrpiq
        app_class: linlin-blog

## Paginate ##
paginate: 7
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

plugins_dir:
   - jekyll-seo-tag
